# fly.toml file generated for acute-armadillo-apigateway on 2023-04-16T23:41:11+02:00

app = "acute-armadillo-apigateway"
primary_region = "cdg"

[http_service]
  internal_port = 80
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
