name: Fly Deploy Frontend
on:
  push:
    branches:
      - release
    paths:
      - 'src/ApiGateways/Web/Web.BFF/**'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_APIGATEWAY }}
jobs:
  deploy:
      name: Deploy frontend
      defaults:
        run:
          working-directory: ./src/ApiGateways/Web/Web.BFF
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy
