name: Frontend Build
on:
  push:
    branches:
      - main
    paths:
      - 'src/Web/Client/**'
jobs:
  deploy:
      name: Build frontend
      defaults:
        run:
          working-directory: ./src/Web/Client
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:headless

      - name: Build
        run: npm run build:prod
